# TODO: consider using pip_install target or docker to hermetize
# the following dependencies:
#    (ai) conda environment (with a lot of packages included)

py_library(
    name = "preprocessing_lib",
    srcs = ["preprocessing.py"],
    deps = ["//machine_learning/common:datasets_lib"],
)
