load("//bazel:angular-bazel.bzl", "ng_app")

# TODO: rethink visibility here
package(default_visibility = ["//visibility:public"])

# The Angular application
# (I moved it from the root BUILD due to my project structure)
ng_app(
    name = "app",
    project_name = "spacebot-app",
)
